version: '3.8'

services:
  mongodb:
    image: mongo:6.0 # Use the required version
    container_name: mongodb_container
    ports:
      - "${DB_PORT}:27017" # Map host port to container port
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER} # Replace with your username
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD} # Replace with your password
    volumes:
      - mongodb_data:/data/db # Persist data using a volume

volumes:
  mongodb_data: # Define the volume

