export enum ElementStatus {
	NOT_ORDERED = 'NOT_ORDERED',
	ORDERED = 'ORDERED',
	IN_DELIVERY = 'IN_DELIVERY',
	READY_FOR_PICKUP = 'READY_FOR_PICKUP',
	RECEIVED = 'RECEIVED',
	AVAILABLE = 'AVAILABLE',
	REQUIRED = 'REQUIRED',
}
