export enum TaskCategory {
	DESIGN = 'DESIGN',
	CONSTRUCTION = 'CONSTRUCTION',
	INSTALLATIONS = 'INSTALLATIONS',
	FINISHING = 'FINISHING',
	CARPENTRY = 'CARPENTRY',
	SMART_HOME = 'SMART_HOME',
	LOGISTICS = 'LOGISTICS',
	CLEANUP = 'CLEANUP',
}
